export const quiz = {
    az: {
        easy: [
            {
                question: "Azərbaycan dilində neçə sait var?",
                A: "A)8",
                B: "B)9",
                C: "C)7",
                D: "D)11",
                correct: "B",
            },
            {
                question: "Azərbaycan dilində neçə samit səs var?",
                A: "A)34",
                B: "B)23",
                C: "C)25",
                D: "D)32",
                correct: "C",
            },
            {
                question:
                    "Hansı kar samitin cingiltili qarşılığı yoxdur?",
                A: "A)H",
                B: "B)F",
                C: "C)G",
                D: "D)C",
                correct: "A",
            },
            {
                question: "Əlifbada neçə hərf var?",
                A: "A)30",
                B: "B)23",
                C: "C)32",
                D: "D)34",
                correct: "C",
            },
            {
                question: "Bitişdirici samitləri göstərin:",
                A: "A)d,t,l",
                B: "B)n,m,s",
                C: "C)m,l,k",
                D: "D)n,y,s",
                correct: "D",
            },
        ],
        medium: [
            {
                question: "Qrammatik cəhətdən feil bildirir?",
                A: "A)Hərəkət",
                B: "B)Xususiyyət",
                C: "C)Keyfiyyət",
                D: "D)Əlamət",
                correct: "A",
            },
            {
                question: "Feilin neçə sadə şəkli var?",
                A: "A)4",
                B: "B)5",
                C: "C)6",
                D: "D)8",
                correct: "C",
            },
            {
                question: "Feil haqqında hansı fikir səhvdir?",
                A: "A)feilin dərəcələri var",
                B: "B)feil hərəkət bildirir",
                C: "C)feil təsirli və təsirsiz olur",
                D: "D)feilin 3 zamanı var",
                correct: "A",
            },
            {
                question: "Feilin quruluşca neçə novu var?",
                A: "A)5",
                B: "B)6",
                C: "C)4",
                D: "D)3",
                correct: "D",
            },
            {
                question:
                    "Feil cümlədə əsasən hansı cümlə üzvü olur?",
                A: "A)təyin",
                B: "B)mübtəda",
                C: "C)xəbər",
                D: "D)zərflik",
                correct: "C",
            },
        ],
        hard: [
            {
                question:
                    "Hansı əlaqə növü bütün tabeli mürəkkəb cümlələrdə olur?",
                A: "A)Qarşılaşdırma",
                B: "B)Zaman",
                C: "C)Səbəb-nəticə",
                D: "D)Heç biri",
                correct: "B",
            },
            {
                question: "Mürəkkəb cümlənin hansı növləri var?",
                A: "A)tabeli, tabesiz",
                B: "B)düzəltmə",
                C: "C)əmr",
                D: "D)sadə",
                correct: "A",
            },
            {
                question: "Mürəkkəb cümlənin neçə novu var?",
                A: "A)6",
                B: "B)2",
                C: "C)5",
                D: "D)3",
                correct: "D",
            },
            {
                question:
                    "Hansı bağlayıcı merəkkəb cümlənin tərəflərini bağlamır?",
                A: "A)ancaq",
                B: "B)ilə",
                C: "C)belə ki",
                D: "D)yəni",
                correct: "B",
            },
            {
                question: "Mürəkkəb cümlələr neçə növə ayrılır?",
                A: "A)2",
                B: "B)4",
                C: "C)5",
                D: "D)3",
                correct: "A",
            },
        ],
    },
    math: {
        easy: [
            {
                question: "5 %-i 2 olan ədədi tap?",
                A: "A)43",
                B: "B)40",
                C: "C)49",
                D: "D)35",
                correct: "A",
            },
            {
                question: "(x+3)+(x+1)=12 Tənliyi həll edin?",
                A: "A)3",
                B: "B)5",
                C: "C)4",
                D: "D)35",
                correct: "C",
            },
            {
                question:
                    "Sürəti 7 olan neçə düzgün olmayan kəsr var?",
                A: "A)7",
                B: "B)32",
                C: "C)4",
                D: "D)6",
                correct: "A",
            },
            {
                question: "4%-i 5,6 olan ədədi tapın:",
                A: "A)48",
                B: "B)400",
                C: "C)49",
                D: "D)140",
                correct: "D",
            },
            {
                question:
                    "0,1(3) sonsuz dövrü onluq kəsrini adi kəsrə çevirin.",
                A: "A)2/15",
                B: "B)26/15",
                C: "C)12/15",
                D: "D)7/15",
                correct: "A",
            },
        ],
        medium: [
            {
                question:
                    "İki ədədin cəmi 5, fərqi 3-dür.Bu ədədlərin hasilini tapın?",
                A: "A)4",
                B: "B)7",
                C: "C)9",
                D: "D)5",
                correct: "A",
            },
            {
                question:
                    "X≠0 olarsa, 2x(x+y)=5y,x(x-y)=y olduqda x-i tapın?",
                A: "A)3/4",
                B: "B)5",
                C: "C)4/9",
                D: "D)38",
                correct: "A",
            },
            {
                question:
                    "x+y=5,x-y=1 olduğuna görə, x2-y2+3x+3y ifadəsinin qiymətini tapın?",
                A: "A)10",
                B: "B)20",
                C: "C)30",
                D: "D)40",
                correct: "B",
            },
            {
                question:
                    "2x+y=5,x-3y=-5 tənliklər sistemindən x+y cəmini tapın?",
                A: "A)4",
                B: "B)7",
                C: "C)3",
                D: "D)5",
                correct: "C",
            },
            {
                question:
                    "x+3=2(y-4),y-2=4x tənliklər sistemindən x-i tapın:",
                A: "A)1/15",
                B: "B)2/15",
                C: "C)3/15",
                D: "D)4/15",
                correct: "B",
            },
        ],
        hard: [
            {
                question: "Hesablayın: (9-2√10)(9+2√10)?",
                A: "A)36",
                B: "B)12",
                C: "C)12√10",
                D: "D)41",
                correct: "D",
            },
            {
                question: "Hesablayın: (3√5+√15)2-10√27?",
                A: "A)80",
                B: "B)70",
                C: "C)60",
                D: "D)50",
                correct: "C",
            },
            {
                question: "√(5+2√6)=?",
                A: "A)√2+√6",
                B: "B)√3+√2",
                C: "C)√5+√2",
                D: "D)√3+√5",
                correct: "B",
            },
            {
                question:
                    "A=√6+1 və b=√6 -1 olduğuna görə, a:b+b:a=?",
                A: "A)2,8",
                B: "B)3,8",
                C: "C)3",
                D: "D)2",
                correct: "A",
            },
            {
                question: "(x-3)2+(y+7)2=0 isə, xy=?",
                A: "A)23",
                B: "B)-32",
                C: "C)21",
                D: "D)-21",
                correct: "D",
            },
        ],
    },
    geography: {
        easy: [
            {
                question: "Hansı ölkə ilə həmsərhəd deyilik?",
                A: "A)Türkiyə",
                B: "B)Qazaxıstan",
                C: "C)Özbəkistan",
                D: "D)Rusiya",
                correct: "C",
            },
            {
                question: "Hansı çay sərhəd çayıdır?",
                A: "A)Kür",
                B: "B)Mazımçay",
                C: "C)Tərtərçay",
                D: "D)Kiş",
                correct: "B",
            },
            {
                question:
                    "Azərbaycan Respublikası hansı qitədə yerləşir?",
                A: "A)Amerika",
                B: "B)Avropa",
                C: "C)Afrika",
                D: "D)Asiya",
                correct: "D",
            },
            {
                question:
                    "Kasıblıq, aşağı təhsil və səhiyyə hansı regiona aiddir?",
                A: "A)Avropa",
                B: "B)Amerika",
                C: "C)Afrika",
                D: "D)Avstraliya",
                correct: "C",
            },
            {
                question: 'Bu ölkə "Böyük yeddiliyə" daxil deyil?',
                A: "A)Yaponiya",
                B: "B)Almaniya",
                C: "C)Fransa",
                D: "D)Ispaniya",
                correct: "D",
            },
        ],
        medium: [
            {
                question: "Miqrasiya adlanır?",
                A: "A)Əhalinin könüllü olaraq başqa ölkəyə köçməsi",
                B: "B)Əhalinin bir yerdən başqa yerə köçməsi",
                C: "C)Əhalinin bir qisminin müvəqqəti şəkildə başqa ölkəyə köçürülməsi",
                D: "D)Əhalinin məcburi şəkildə ölkədən çıxarılması",
                correct: "B",
            },
            {
                question:
                    "ABŞ – a immiqrantlar başlıca olaraq gəlirlər:",
                A: "A)Latın Amerikasından, Asiyadan və Avropadan",
                B: "B)Hindistandan, Kanadadan, Afrikadan",
                C: "C)Cənubi Avropadan, Şimali Afrikadan, MDB ölkələrindən",
                D: "D)Hindistandan, Pakistandan, Misirdən",
                correct: "A",
            },
            {
                question:
                    "Hind – Avropa dil ailəsinə aid olmayan dil qrupu?",
                A: "A)Qafqaz",
                B: "B)Slavyan",
                C: "C)Iran",
                D: "D)Roman",
                correct: "A",
            },
            {
                question: "Birmillətli dövlət deyil?",
                A: "A)Niderland",
                B: "B)Norveç",
                C: "C)Türkiyə",
                D: "D)Yaponiya",
                correct: "C",
            },
            {
                question: "Hansı dünyəvi dindir?",
                A: "A)Iudaizm",
                B: "B)Sintoizm",
                C: "C)Lamaizm",
                D: "D)Buddizm",
                correct: "D",
            },
        ],
        hard: [
            {
                question: "Mərkəzi Amerika regionuna aid deyil?",
                A: "A)Meksika",
                B: "B)Beliz",
                C: "C)Honduras",
                D: "D)Çili",
                correct: "D",
            },
            {
                question: "Ən çox əhalisi olan ölkə?",
                A: "A)Kolumbiya",
                B: "B)Meksika",
                C: "C)Braziliya",
                D: "D)Argentina",
                correct: "C",
            },
            {
                question:
                    "Latın Amerikasında ən geniş yayılmış dil hansıdır?",
                A: "A)Portuqal",
                B: "B)İngilis",
                C: "C)İtalyan",
                D: "D)İspan",
                correct: "D",
            },
            {
                question: "Çinin əhalisi?",
                A: "A)2,101,3 mln. nəfər",
                B: "B)1,761,3 mln. nəfər",
                C: "C)2, 243, 7 mln. nəfər",
                D: "D)1,348,6 mln. nəfər",
                correct: "D",
            },
            {
                question:
                    "Ən çox əhalisi olan Mərkəzi Asiya ölkəsi?",
                A: "A)Qırğızıstan",
                B: "B)Türkmənistan",
                C: "C)Özbəkistan",
                D: "D)Qazaxıstan",
                correct: "C",
            },
        ],
    },
};